const { Router } = require('express')
const usersMiddleware = require('./users')
const storesMiddleware = require('./stores')
const schedulesMiddleware = require('./schedules')
const scheduleHoursMiddleware = require('./scheduleHours')
const ordersMiddleware = require('./orders')
const pizzasMiddleware = require('./pizzas')
const pizzaIngredientsMiddleware = require('./pizzaIngredients')
const pizzaMassesMiddleware = require('./pizzaMasses')
const pizzaSizesMiddleware = require('./pizzaSizes')
const pizzaExtraIngredientsMiddleware = require('./pizzaExtraIngredients')
const pizzaCharacteristicsMiddleware = require('./pizzaCharacteristics')
const checkoutMiddleware = require('./checkout')

const router = Router()
router.use('/checkout', checkoutMiddleware)
router.use('/users', usersMiddleware)
router.use('/stores', storesMiddleware)
router.use('/schedules', schedulesMiddleware)
router.use('/scheduleHours', scheduleHoursMiddleware)
router.use('/orders', ordersMiddleware)
router.use('/pizzas', pizzasMiddleware)
router.use('/pizzaIngredients', pizzaIngredientsMiddleware)
router.use('/pizzaMasses', pizzaMassesMiddleware)
router.use('/pizzaSizes', pizzaSizesMiddleware)
router.use('/pizzaCharacteristics', pizzaCharacteristicsMiddleware)
router.use('/pizzaExtraIngredients', pizzaExtraIngredientsMiddleware)

module.exports = router